language: node_js
node_js:
  - "stable"
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: polaroid-client
  on:
    repo: malcodeman/polaroid-client
